custom: ['https://www.paypal.com/donate/?business=MTMKXMHQZU7LL&no_recurring=1&item_name=Thanks+for+considering+donating+to+me%21+Every+cent+counts+and+ensures+I+can+continue+my+education+and+update+my+mods+asap+%3A%29&currency_code=BRL']
